# Generated by Django 4.1.3 on 2022-12-08 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('posts', '0004_remove_post_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='occupations',
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(related_name='posts', to='categories.category'),
        ),
        migrations.DeleteModel(
            name='Occupation',
        ),
    ]
