# Generated by Django 4.1.3 on 2022-12-14 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_resume'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Resume',
        ),
    ]
