# Generated by Django 4.1.3 on 2022-11-25 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("addresses", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="address_type",
            field=models.CharField(
                choices=[("work_place", "WorkPlace"), ("company", "Company")],
                max_length=10,
            ),
        ),
    ]
