# Generated by Django 4.1.3 on 2022-11-27 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("addresses", "0003_alter_address_address_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="address_type",
            field=models.CharField(
                choices=[
                    ("company", "Company"),
                    ("user", "User"),
                    ("workplace", "WorkPlace"),
                ],
                max_length=10,
            ),
        ),
    ]
