# Generated by Django 4.1.3 on 2022-11-25 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("addresses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Occupation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Workplace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                ("working_day", models.CharField(max_length=100)),
                ("working_start_time", models.TimeField()),
                ("working_end_time", models.TimeField()),
                ("working_hours", models.IntegerField()),
                (
                    "salary_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("hourly", "시급"),
                            ("daily", "일급"),
                            ("monthly", "월급"),
                            ("yearly", "연봉"),
                        ],
                        max_length=7,
                    ),
                ),
                ("salary", models.PositiveIntegerField(blank=True, null=True)),
                ("benefits", models.TextField(blank=True)),
                (
                    "Occupation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workplaces",
                        to="workplaces.occupation",
                    ),
                ),
                (
                    "address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workplaces",
                        to="addresses.address",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
