# Generated by Django 4.1.3 on 2022-11-25 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workplaces", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkDayOfWeek",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RenameField(
            model_name="workplace",
            old_name="working_end_time",
            new_name="off_work_time",
        ),
        migrations.RenameField(
            model_name="workplace",
            old_name="working_start_time",
            new_name="start_work_time",
        ),
        migrations.RemoveField(
            model_name="workplace",
            name="working_day",
        ),
        migrations.AddField(
            model_name="workplace",
            name="work_days_of_week",
            field=models.ManyToManyField(
                related_name="workplaces", to="workplaces.workdayofweek"
            ),
        ),
    ]
