# Generated by Django 4.1.3 on 2022-11-25 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workplaces", "0002_workdayofweek_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Benefit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RemoveField(
            model_name="workplace",
            name="benefits",
        ),
        migrations.AddField(
            model_name="workplace",
            name="benefits",
            field=models.ManyToManyField(
                related_name="workplaces", to="workplaces.benefit"
            ),
        ),
    ]
