# Generated by Django 4.1.3 on 2022-11-25 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workplaces", "0003_benefit_remove_workplace_benefits_workplace_benefits"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workplace",
            name="Occupation",
        ),
        migrations.AddField(
            model_name="workplace",
            name="occupations",
            field=models.ManyToManyField(
                related_name="workplaces", to="workplaces.occupation"
            ),
        ),
    ]
