# Generated by Django 4.1.3 on 2022-11-29 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workplaces", "0004_remove_workplace_occupation_workplace_occupations"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workplace",
            name="occupations",
        ),
        migrations.DeleteModel(
            name="Occupation",
        ),
    ]
