# Generated by Django 4.1.3 on 2022-12-08 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_alter_category_kind'),
        ('workplaces', '0005_remove_workplace_occupations_delete_occupation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workplace',
            name='benefits',
        ),
        migrations.AddField(
            model_name='workplace',
            name='benefit',
            field=models.ManyToManyField(related_name='workplaces', to='categories.category'),
        ),
        migrations.DeleteModel(
            name='Benefit',
        ),
    ]
