# Generated by Django 4.1.3 on 2022-12-14 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='content',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
