# Generated by Django 4.1.3 on 2022-12-14 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0002_alter_resume_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='is_confirm',
            field=models.BooleanField(default=False),
        ),
    ]
