# Generated by Django 4.1.3 on 2022-11-28 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0002_alter_company_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="company_type",
            field=models.CharField(
                choices=[("contractor", "Contractor"), ("agency", "Agency")],
                default="contractor",
                max_length=10,
            ),
        ),
    ]
