# Generated by Django 4.1.3 on 2022-11-27 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("people_in_charge", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="personincharge",
            options={"verbose_name_plural": "People in charge"},
        ),
    ]
